public enum SongsName {

    BLACKSMITH_ARM,
    DEAR_MR_HARRISON,
    EMBARK,
    HONEY_N_BISCUITS,
    HOW_ORE_YOU_TODAY,
    IRONWOOD_LEAVES,
    MORNING_CHORES,
    POTTERS_SPRINT,
    SNEAKY_THE_SMUGGLER,
    SOUP_OF_THE_DAY,
    THE_BUTTERFLY,
    WEAVERS_WEBB,
    WINDSWARD_INN,
    WYRDWOOD_LEAVES

}
